---

- name: Add the PostgreSQL repository key to the apt trusted keys
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
           state=present

- name: Add the PostgreSQL repository to the apt sources list
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'
                  update_cache=yes
                  state=present

- name: Ensure locale is available
  locale_gen: name=en_US.UTF-8

- name: Install PostgreSQL
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - "postgresql-{{postgresql_version}}"
    - "postgresql-client-{{postgresql_version}}"
    - "postgresql-contrib-{{postgresql_version}}"

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Install postgis
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - binutils
    - libproj-dev
    - gdal-bin
    - postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}
    - postgresql-server-dev-{{ postgresql_version }}
  when: postgis_enabled
  tags:
    - geodjango